#%RAML 1.0 DataType
type: object
properties:
  notificationId?: string
  sourceStation: string
  destinationStation: string
  trainName: string
  actualTime: datetime
  estimatedTime: datetime