#%RAML 1.0 NamedExample

[
  {
  "customerId": "101",
  "userId": "ddx",
  "firstName": "Ravi",
  "lastName": "Teja",
  "emailId": "raviteja@gmail.com",
  "phone": "07448772079"
  },
  {
  "customerId": "101",
   "userId": "ddx",
  "firstName": "Ravi",
  "lastName": "Teja",
  "emailId": "raviteja@gmail.com",
  "phone": "07448772079"
  }
]