#%RAML 1.0 NamedExample
notification-example:
value:
    notificationId: "6318"
    sourceStation: Liverpool
    destinationStation: Cambridge
    trainName: National trian-2465
    actualTime: 2016-02-28T16:41:41.090Z
    estimatedTime: 2016-02-28T17:41:41.090Z