#%RAML 1.0 NamedExample
  [
    {
  "subscription": "1254",
  "customerId": "12",
  "source": "cambridge",
  "destination": "Liverpool",
  "sourceTime": "2016-02-28T12:41:41.090Z",
  "destinationTime": "2016-02-28T16:41:41.090Z", 
  "remainderTime": "00:30:00"
   },
  
    {
  "subscription": "1254",
  "customerId": "12",
  "source": "cambridge",
  "destination": "Liverpool",
  "sourceTime": "2016-02-28T12:41:41.090Z",
  "destinationTime": "2016-02-28T16:41:41.090Z", 
  "remainderTime": "00:30:00"
    }
  ]